### ISSUE TITLE
RSpecs for `Rails` 4 does not work in `ruby 2.7.8`

### ISSUE THREAD

**Issue by the-teacher** [TheRole/the_role_dev#15]
<img width="1510" alt="Screenshot 2023-07-08 at 16 16 56" src="https://github.com/TheRole/the_role_dev/assets/496713/e00ca5f5-651c-403e-884c-7449fa118fc4">

```sh
 WelcomeController GET for GUESTS *INDEX* returns http success
      Failure/Error: initialize

      ThreadError:
        already initialized
      # ./spec/rails_helper.rb:25:in `recycle!'
      # /usr/local/bundle/gems/devise-4.9.2/lib/devise/test/controller_helpers.rb:35:in `block in process'
      # /usr/local/bundle/gems/devise-4.9.2/lib/devise/test/controller_helpers.rb:104:in `catch'
      # /usr/local/bundle/gems/devise-4.9.2/lib/devise/test/controller_helpers.rb:104:in `_catch_warden'
      # /usr/local/bundle/gems/devise-4.9.2/lib/devise/test/controller_helpers.rb:35:in `process'
      # /home/the_role_dev/the_role_specs/specs/controllers/welcome_controller_spec.rb:11:in `block (3 levels) in <top (required)>'
```

**Comment by the-teacher** [comment]
I downgraded to `ruby:2.6.10`
